services:
  app:
    build: .
    container_name: php_app_container
    volumes:
      - .:/var/www
      # Anonymous volume to keep the container's vendor folder separate from the host
      - /var/www/vendor
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: php artisan serve --host=0.0.0.0 --port=8000
